<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>TrustApi</RootNamespace>
    <AssemblyName>TrustApi</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.4" />
    <PackageReference Include="Microsoft.IdentityModel.Protocols.OpenIdConnect" Version="8.8.0" />
    <PackageReference Include="Npgsql" Version="9.0.4" />
    <PackageReference Include="Stripe.net" Version="52.4.0" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="TrustApi.Tests/**/*.cs" />
    <Content Remove="TrustApi.Tests/**" />
    <None Remove="TrustApi.Tests/**" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Infrastructure/Postgres/Migrations/*.sql" />
    <EmbeddedResource Include="Infrastructure/StoreKit/AppleRootCA-G3.cer" />
  </ItemGroup>

</Project>
